"""
Ground truth from cash flow tables (in millions).

Amazon:
  Operating cash flow (FY 2024 TTM): 115,877
  Free cash flow (FY 2024 TTM): 38,219  (from Supplemental table)
  CapEx - purchases of property and equipment (FY 2024): 82,999

Apple:
  Cash generated by operating activities (9M 2024): 91,443
  CapEx - payments for acquisition of property, plant and equipment (9M 2024): 6,539
  Free cash flow (9M 2024): 91,443 - 6,539 = 84,904
"""


class TestAmazonCashFlowCapex:
    def test_operating_cash_flow(self, amzn):
        assert amzn["cash_flow"]["operating_cash_flow"] == 115877

    def test_free_cash_flow(self, amzn):
        assert amzn["cash_flow"]["free_cash_flow"] == 38219

    def test_total_capex(self, amzn):
        assert amzn["capex"]["total_capex"] == 82999


class TestAppleCashFlowCapex:
    def test_operating_cash_flow(self, aapl):
        assert aapl["cash_flow"]["operating_cash_flow"] == 91443

    def test_free_cash_flow(self, aapl):
        assert aapl["cash_flow"]["free_cash_flow"] == 84904

    def test_total_capex(self, aapl):
        assert aapl["capex"]["total_capex"] == 6539
